/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaarchivos;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static practicaarchivos.Evaluador.archdem2;

/**
 *
 * @author woltmannj
 */
public class Demanda extends javax.swing.JFrame {

    
    String infor;
    public static File archdem = new File("Demandas.txt");
    String habilidad = "", val = "";
    Oferta o;
    

    /**
     * Creates new form Vista
     */
    public Demanda() {
        initComponents();
        this.mostrartabla();
        addbutton.setToolTipText("Añadir");
        elimbutton.setToolTipText("Eliminar");
        cleanbutton.setToolTipText("Limpiar");
        Backbutton.setToolTipText("Volver");
        SaveButton.setToolTipText("Guardar");
        OpenButton.setToolTipText("Abrir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombretf = new javax.swing.JTextField();
        Emailtf = new javax.swing.JTextField();
        Salariotf = new javax.swing.JTextField();
        Completa = new javax.swing.JCheckBox();
        insertar = new javax.swing.JButton();
        Parcial = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Titulacion = new javax.swing.JComboBox<>();
        nivelhc = new javax.swing.JComboBox<>();
        seglen = new javax.swing.JCheckBox();
        projava = new javax.swing.JCheckBox();
        habcom = new javax.swing.JCheckBox();
        lider = new javax.swing.JCheckBox();
        crea = new javax.swing.JCheckBox();
        ningu = new javax.swing.JCheckBox();
        nivell = new javax.swing.JComboBox<>();
        nivelc = new javax.swing.JComboBox<>();
        nivelpj = new javax.swing.JComboBox<>();
        Nivelsl = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        fc = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        addbutton = new javax.swing.JButton();
        elimbutton = new javax.swing.JButton();
        cleanbutton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        OpenButton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();

        frame.setMinimumSize(new java.awt.Dimension(768, 348));
        frame.setResizable(false);

        jLabel1.setText("Salario");

        jLabel2.setText("Nombre");

        jLabel3.setText("e-mail");

        jLabel4.setText("Jornada");

        Nombretf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretfActionPerformed(evt);
            }
        });
        Nombretf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombretfKeyTyped(evt);
            }
        });

        Emailtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtfActionPerformed(evt);
            }
        });
        Emailtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailtfKeyTyped(evt);
            }
        });

        Salariotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalariotfKeyTyped(evt);
            }
        });

        Completa.setText("Completa");

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        Parcial.setText("Parcial");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Habilidades");

        jLabel6.setText("Titulaciones");

        Titulacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja la titulación", "Bachiller", "Tecnico en sistemas", "Ingeniero de sistemas", "Ingeniero industrial", "Ingeniero electronico", "Ingeniero electrico", "Ingeniero ambienta", "Ingeniero mecanicol", "Medico", "Contador", "Administrador de empresas", "Diseñador Grafico", "Diseñador industrial", "Matemático", "Comunicador social", " " }));
        Titulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitulacionActionPerformed(evt);
            }
        });

        nivelhc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja valoracion", "1", "2", "3", "4", "5" }));
        nivelhc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelhcActionPerformed(evt);
            }
        });

        seglen.setText("Segunda Lengua");
        seglen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seglenActionPerformed(evt);
            }
        });

        projava.setText("Programación en java");
        projava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projavaActionPerformed(evt);
            }
        });

        habcom.setText("Habilidades comunicativas");

        lider.setText("Líder");

        crea.setText("Creativo");

        ningu.setText("Ninguna");

        nivell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja valoracion", "1", "2", "3", "4", "5" }));
        nivell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivellActionPerformed(evt);
            }
        });

        nivelc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja valoracion", "1", "2", "3", "4", "5" }));
        nivelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelcActionPerformed(evt);
            }
        });

        nivelpj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja valoracion", "1", "2", "3", "4", "5" }));
        nivelpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelpjActionPerformed(evt);
            }
        });

        Nivelsl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja valoracion", "1", "2", "3", "4", "5" }));
        Nivelsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelslActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Emailtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(Salariotf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombretf)))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Titulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Completa)
                        .addGap(18, 18, 18)
                        .addComponent(Parcial))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(insertar)
                        .addGap(26, 26, 26)
                        .addComponent(cancelar)))
                .addGap(32, 32, 32)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ningu)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projava)
                            .addComponent(seglen))
                        .addGap(30, 30, 30)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nivelsl, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelpj, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habcom)
                            .addComponent(lider)
                            .addComponent(crea))
                        .addGap(10, 10, 10)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelhc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nombretf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)))
                .addGap(8, 8, 8)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Salariotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Completa)
                            .addComponent(Parcial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Titulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertar)
                            .addComponent(cancelar)))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameLayout.createSequentialGroup()
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seglen)
                                    .addComponent(Nivelsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(projava)
                                    .addComponent(nivelpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(habcom)
                                .addComponent(nivelhc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lider)
                            .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nivelc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ningu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "e-mail", "Salario min", "Jornada completa", "Jornada parcial", "Titulaciones", "Habilidadesl", "Valoracion de Ac"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
            Tabla.getColumnModel().getColumn(4).setResizable(false);
            Tabla.getColumnModel().getColumn(5).setResizable(false);
            Tabla.getColumnModel().getColumn(6).setResizable(false);
            Tabla.getColumnModel().getColumn(7).setResizable(false);
        }

        addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/agregar-usuario.png"))); // NOI18N
        addbutton.setBorder(null);
        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        elimbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/borrar.png"))); // NOI18N
        elimbutton.setBorder(null);
        elimbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elimbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimbuttonActionPerformed(evt);
            }
        });

        cleanbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/escoba.png"))); // NOI18N
        cleanbutton.setBorder(null);
        cleanbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanbuttonActionPerformed(evt);
            }
        });

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/disquete.png"))); // NOI18N
        SaveButton.setBorder(null);
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        OpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/sobre-abierto.png"))); // NOI18N
        OpenButton.setBorder(null);
        OpenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/volver.png"))); // NOI18N
        Backbutton.setBorder(null);
        Backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addbutton)
                .addGap(18, 18, 18)
                .addComponent(elimbutton)
                .addGap(18, 18, 18)
                .addComponent(cleanbutton)
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(OpenButton)
                .addGap(299, 299, 299)
                .addComponent(Backbutton)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpenButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(elimbutton)
                        .addComponent(addbutton))
                    .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cleanbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Backbutton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        Nombretf.setText("");
        Emailtf.setText("");
        Salariotf.setText("");
        Completa.setSelected(false);
        Parcial.setSelected(true);
        Titulacion.setSelectedIndex(0);
        seglen.setSelected(false);
        projava.setSelected(false);
        habcom.setSelected(false);
        lider.setSelected(false);
        crea.setSelected(false);
        ningu.setSelected(false);
        nivelpj.setSelectedIndex(0);
        nivell.setSelectedIndex(0);
        nivelc.setSelectedIndex(0);
        nivelhc.setSelectedIndex(0);
        Nivelsl.setSelectedIndex(0);
        frame.setBounds(50, 50, 310, 390);
        frame.setVisible(true);
    }//GEN-LAST:event_addbuttonActionPerformed
    public boolean verificarhabilidades() {
        if ((projava.isSelected() && nivelpj.getSelectedIndex() != 0) || (habcom.isSelected() && nivelhc.getSelectedIndex() != 0)
                || (seglen.isSelected() && Nivelsl.getSelectedIndex() != 0) || (ningu.isSelected())
                || (lider.isSelected() && nivell.getSelectedIndex() != 0) || (crea.isSelected() && nivelc.getSelectedIndex() != 0)) {
            return true;
        } else {
            return false;
        }
    }

    public void mostrartabla() {
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        if (archdem.exists()) {
            try (Scanner leer = new Scanner(archdem)) {
                while (leer.hasNextLine()) {

                    String linea = leer.nextLine();
                    String[] Datos = linea.split(",");
                    String nom = (Datos[0]);
                    String email = Datos[1];
                    long sal = Long.parseLong(Datos[2]);
                    boolean completa = Boolean.parseBoolean(Datos[3]);
                    boolean parcial = Boolean.parseBoolean(Datos[4]);
                    String titulaciones = (Datos[5]);
                    String habilidad = (Datos[6]);
                    String val = (Datos[7]);

                    table.addRow(new Object[]{nom, email, sal, completa, parcial, titulaciones, habilidad, val});

                }
                leer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Demanda.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        if ((Nombretf.getText().equals("")) || (Salariotf.getText().equals(""))
                || (Parcial.isSelected() == false && Completa.isSelected() == false) || this.verificarhabilidades() == false
                || Titulacion.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(null, "llene todos los campos");
        } else {

            String nom = (Nombretf.getText());
            String email = Emailtf.getText();
            long sal = Long.parseLong(Salariotf.getText());
            boolean completa = Completa.isSelected();
            boolean parcial = Parcial.isSelected();
            String titulaciones = Titulacion.getSelectedItem().toString();
            habilidad="";
            val="";
            if (Nivelsl.getSelectedItem().toString() != "Escoja valoracion" && seglen.isSelected()) {
                habilidad = habilidad + "segunda lengua ";
                val = val + Nivelsl.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }

            if (nivelpj.getSelectedItem().toString() != "Escoja valoracion" && projava.isSelected()) {
                habilidad = habilidad + "programacionjava ";
                val = val + nivelpj.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (nivelhc.getSelectedItem().toString() != "Escoja valoracion" && habcom.isSelected()) {
                habilidad = habilidad + "habilidadescomunicativas ";
                val = val + nivelhc.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (nivell.getSelectedItem().toString() != "Escoja valoracion" && lider.isSelected()) {
                habilidad = habilidad + "lider ";
                val = val + nivell.getSelectedItem().toString() + "";
            } else {
                val= val + "0 ";
            }
            if (nivelc.getSelectedItem().toString() != "Escoja valoracion" && crea.isSelected()) {
                habilidad = habilidad + "creativo ";
                val = val + nivelc.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (ningu.isSelected()) {
                habilidad = "ninguno";
                val = "0 0 0 0 0 ";

            }

            DefaultTableModel table = (DefaultTableModel) Tabla.getModel();

            table.addRow(new Object[]{nom, email, sal, completa, parcial, titulaciones, habilidad, val});
            frame.setVisible(false);

        }

    }//GEN-LAST:event_insertarActionPerformed

    private void elimbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimbuttonActionPerformed
    if (Tabla.getSelectedRow() == -1){JOptionPane.showMessageDialog(null,"Favor seleccione una fila");}else{
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        table.removeRow(Tabla.getSelectedRow());
        }
    }//GEN-LAST:event_elimbuttonActionPerformed

    private void cleanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanbuttonActionPerformed
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        table.setRowCount(0);
    }//GEN-LAST:event_cleanbuttonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (!archdem.exists()) {
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .txt", "txt");
            fc.setFileFilter(filtro);
            int opcion = fc.showSaveDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                archdem = fc.getSelectedFile();
            }
        }
        int filas = Tabla.getRowCount();
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        try (FileWriter fw = new FileWriter(archdem);
                BufferedWriter bw = new BufferedWriter(fw);) {
            for (int i = 0; i < filas; i++) {
                Object nom = table.getValueAt(i, 0);
                Object email = table.getValueAt(i, 1);
                Object sal = table.getValueAt(i, 2);
                Object completa = table.getValueAt(i, 3);
                Object parcial = table.getValueAt(i, 4);
                Object titulaciones = table.getValueAt(i, 5);
                Object habilidad = table.getValueAt(i, 6);
                Object val = table.getValueAt(i, 7);
                bw.write(nom + "," + email + "," + sal + "," + completa + "," + parcial + "," + titulaciones + "," + habilidad + "," + val);
                bw.newLine();

            }
            bw.close();
            JOptionPane.showMessageDialog(null, "Guardado");
        } catch (IOException ex) {
            Logger.getLogger(Demanda.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .txt", "txt");
        fc.setFileFilter(filtro);
        int opcion = fc.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            archdem = fc.getSelectedFile();
            DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
            try (Scanner leer = new Scanner(archdem)) {
                while (leer.hasNextLine()) {

                    String linea = leer.nextLine();
                    String[] Datos = linea.split(",");
                    String nom = (Datos[0]);
                    String email = Datos[1];
                    long sal = Long.parseLong(Datos[2]);
                    boolean completa = Boolean.parseBoolean(Datos[3]);
                    boolean parcial = Boolean.parseBoolean(Datos[4]);
                    String titulaciones = (Datos[5]);
                    String habilidad = (Datos[6]);
                    String val = (Datos[7]);

                    table.addRow(new Object[]{nom, email, sal, completa, parcial, titulaciones, habilidad, val});

                }
                leer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Demanda.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_OpenButtonActionPerformed

    private void TablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaPropertyChange

    private void TitulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulacionActionPerformed

    private void NombretfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombretfKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && ((int) evt.getKeyChar() != 32)) {
            evt.consume();
        }    }//GEN-LAST:event_NombretfKeyTyped

    private void SalariotfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalariotfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_SalariotfKeyTyped

    private void EmailtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailtfKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') &&  ((int) (evt.getKeyChar()) != 196) && ((int) (evt.getKeyChar()) != 95) && ((int) (evt.getKeyChar())==44)) {
            evt.consume();
        }
    }//GEN-LAST:event_EmailtfKeyTyped

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        this.dispose();
        Inicio i = new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void EmailtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailtfActionPerformed

    private void nivelhcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelhcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelhcActionPerformed

    private void projavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projavaActionPerformed

    private void seglenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seglenActionPerformed

    }//GEN-LAST:event_seglenActionPerformed

    private void nivellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivellActionPerformed

    private void nivelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelcActionPerformed

    private void nivelpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelpjActionPerformed

    private void NivelslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelslActionPerformed


    }//GEN-LAST:event_NivelslActionPerformed

    private void NombretfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretfActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JCheckBox Completa;
    private javax.swing.JTextField Emailtf;
    private javax.swing.JComboBox<String> Nivelsl;
    private javax.swing.JTextField Nombretf;
    private javax.swing.JButton OpenButton;
    private javax.swing.JCheckBox Parcial;
    private javax.swing.JTextField Salariotf;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox<String> Titulacion;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cleanbutton;
    private javax.swing.JCheckBox crea;
    private javax.swing.JButton elimbutton;
    private javax.swing.JFileChooser fc;
    private javax.swing.JFrame frame;
    private javax.swing.JCheckBox habcom;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox lider;
    private javax.swing.JCheckBox ningu;
    private javax.swing.JComboBox<String> nivelc;
    private javax.swing.JComboBox<String> nivelhc;
    private javax.swing.JComboBox<String> nivell;
    private javax.swing.JComboBox<String> nivelpj;
    private javax.swing.JCheckBox projava;
    private javax.swing.JCheckBox seglen;
    // End of variables declaration//GEN-END:variables
}
