/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaarchivos;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import static practicaarchivos.Empresa.archemp;
import static practicaarchivos.Empresa.frame;

/**
 *
 * @author woltmannj
 */
public class Oferta extends javax.swing.JFrame {

   public static File arch = new File("Ofertas.txt");
    String val = "", habilidad = "", salmin = "0";
  

    /**
     * Creates new form Vista
     */
    public Oferta() throws IOException {
        initComponents();
        this.mostartabla2();
        addbutton.setToolTipText("Añadir");
        elimbutton.setToolTipText("Eliminar");
        cleanbutton.setToolTipText("Limpiar");
        backbutton.setToolTipText("Volver");
        SaveButton.setToolTipText("Guardar");
        OpenButton.setToolTipText("Abrir");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombretf = new javax.swing.JTextField();
        Salmintf = new javax.swing.JTextField();
        Salmaxtf = new javax.swing.JTextField();
        Parcial = new javax.swing.JCheckBox();
        insertar = new javax.swing.JButton();
        Completa = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Titulacion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        crea = new javax.swing.JCheckBox();
        habcom = new javax.swing.JCheckBox();
        projava = new javax.swing.JCheckBox();
        lider = new javax.swing.JCheckBox();
        seglen = new javax.swing.JCheckBox();
        Nivelsl = new javax.swing.JComboBox<>();
        nivelpj = new javax.swing.JComboBox<>();
        nivelhc = new javax.swing.JComboBox<>();
        nivell = new javax.swing.JComboBox<>();
        nivelc = new javax.swing.JComboBox<>();
        ningu = new javax.swing.JCheckBox();
        cancelar = new javax.swing.JButton();
        nempcb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fc = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        addbutton = new javax.swing.JButton();
        elimbutton = new javax.swing.JButton();
        cleanbutton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        OpenButton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        frame.setMinimumSize(new java.awt.Dimension(258, 258));
        frame.setResizable(false);

        jLabel1.setText("Salario Máximo:");

        jLabel2.setText("Nombre/Descripcion");

        jLabel3.setText("Salario Mínimo");

        jLabel4.setText("Jornada");

        Nombretf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nombretf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretfActionPerformed(evt);
            }
        });
        Nombretf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombretfKeyTyped(evt);
            }
        });

        Salmintf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalmintfActionPerformed(evt);
            }
        });
        Salmintf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalmintfKeyTyped(evt);
            }
        });

        Salmaxtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalmaxtfKeyTyped(evt);
            }
        });

        Parcial.setText("Parcial");

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        Completa.setText("Completa");

        jLabel5.setText("Titulaciones");

        Titulacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja la titulación", "Bachiller", "Tecnico en sistemas", "Ingeniero de sistemas", "Ingeniero industrial", "Ingeniero electronico", "Ingeniero electrico", "Ingeniero ambienta", "Ingeniero mecanicol", "Medico", "Contador", "Administrador de empresas", "Diseñador Grafico", "Diseñador industrial", "Matemático", "Comunicador social" }));
        Titulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitulacionActionPerformed(evt);
            }
        });

        jLabel8.setText("Escoja la habilidad que desea de sus empleados");

        crea.setText("Creativo");

        habcom.setText("Habilidades comunicativas");

        projava.setText("Programacion en java");

        lider.setText("Líder");

        seglen.setText("Segunda lengua");
        seglen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seglenActionPerformed(evt);
            }
        });

        Nivelsl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja nivel", "1", "2", "3", "4", "5" }));
        Nivelsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelslActionPerformed(evt);
            }
        });

        nivelpj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja nivel", "1", "2", "3", "4", "5" }));
        nivelpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelpjActionPerformed(evt);
            }
        });

        nivelhc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja nivel", "1", "2", "3", "4", "5" }));
        nivelhc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelhcActionPerformed(evt);
            }
        });

        nivell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja nivel", "1", "2", "3", "4", "5" }));
        nivell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivellActionPerformed(evt);
            }
        });

        nivelc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja nivel", "1", "2", "3", "4", "5" }));
        nivelc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelcActionPerformed(evt);
            }
        });

        ningu.setText("Ninguna");
        ningu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninguActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        nempcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja empresa" }));
        nempcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nempcbActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione empresa");

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(frameLayout.createSequentialGroup()
                                .addComponent(Completa)
                                .addGap(54, 54, 54)
                                .addComponent(Parcial))
                            .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Salmaxtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(Salmintf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nombretf, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nempcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crea)
                            .addComponent(lider)
                            .addComponent(habcom)
                            .addComponent(projava)
                            .addComponent(seglen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nivelsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelhc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ningu)
                            .addComponent(jLabel8))
                        .addGap(79, 79, 79))))
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(insertar)
                .addGap(112, 112, 112)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seglen)
                            .addComponent(Nivelsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projava)
                            .addComponent(nivelpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nombretf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Salmintf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frameLayout.createSequentialGroup()
                            .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(Salmaxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                            .addComponent(habcom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                        .addComponent(nivelhc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Parcial)
                        .addComponent(Completa))
                    .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lider, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nivelc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ningu)
                        .addGap(51, 51, 51))
                    .addGroup(frameLayout.createSequentialGroup()
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Titulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nempcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertar)
                    .addComponent(cancelar))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre/Descripción  ", "Salario Min", "Salario Max", "J. Parcial ", "J. Completa", "Titulaciones", "Habilidades", "Nivel ", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
            Tabla.getColumnModel().getColumn(4).setResizable(false);
            Tabla.getColumnModel().getColumn(5).setResizable(false);
            Tabla.getColumnModel().getColumn(6).setResizable(false);
            Tabla.getColumnModel().getColumn(7).setResizable(false);
            Tabla.getColumnModel().getColumn(8).setResizable(false);
        }

        addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/agregar-usuario.png"))); // NOI18N
        addbutton.setBorder(null);
        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbuttonMouseEntered(evt);
            }
        });
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        elimbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/borrar.png"))); // NOI18N
        elimbutton.setBorder(null);
        elimbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elimbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimbuttonActionPerformed(evt);
            }
        });

        cleanbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/escoba.png"))); // NOI18N
        cleanbutton.setBorder(null);
        cleanbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanbuttonActionPerformed(evt);
            }
        });

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/disquete.png"))); // NOI18N
        SaveButton.setBorder(null);
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        OpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/sobre-abierto.png"))); // NOI18N
        OpenButton.setBorder(null);
        OpenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaarchivos/iconos/volver.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(addbutton)
                .addGap(18, 18, 18)
                .addComponent(elimbutton)
                .addGap(18, 18, 18)
                .addComponent(cleanbutton)
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(OpenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpenButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cleanbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elimbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addbutton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        Nombretf.setText("");
        Salmintf.setText("0");
        Salmaxtf.setText("0");
        Parcial.setSelected(false);
        Completa.setSelected(true);
        Titulacion.setSelectedIndex(0);
        seglen.setSelected(false);
        projava.setSelected(false);
        habcom.setSelected(false);
        lider.setSelected(false);
        crea.setSelected(false);
        ningu.setSelected(false);
        nivelpj.setSelectedIndex(0);
        nivell.setSelectedIndex(0);
        nivelc.setSelectedIndex(0);
        nivelhc.setSelectedIndex(0);
        Nivelsl.setSelectedIndex(0);
        nempcb.removeAllItems();
        nempcb.addItem("Escoja empresa");
        nempcb.setSelectedIndex(0);
        try {
            this.insertarempresa();
        } catch (IOException ex) {
            Logger.getLogger(Oferta.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setBounds(50, 50, 750, 400);
        frame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_addbuttonActionPerformed
    public boolean verificarhabilidades() {
        if ((projava.isSelected() && nivelpj.getSelectedIndex() != 0) || (habcom.isSelected() && nivelhc.getSelectedIndex() != 0)
                || (seglen.isSelected() && Nivelsl.getSelectedIndex() != 0) || (ningu.isSelected())
                || (lider.isSelected() && nivell.getSelectedIndex() != 0) || (crea.isSelected() && nivelc.getSelectedIndex() != 0) /*|| (nempcb.getSelectedIndex() != 0)*/) {
            return true;
        } else {
            return false;
        }
    }

    public void insertarempresa() throws FileNotFoundException, IOException {
        if (archemp.exists()) {
            FileReader fr = new FileReader(archemp);
            BufferedReader br = new BufferedReader(fr);
            String x;
            while ((x = br.readLine()) != null) {
                if (x.contains(",")) {
                    int n = x.indexOf(",");
                    String nombre = x.substring(0, n);
                    nempcb.addItem(nombre);
                }
            }
            br.close();
        }
    }

    public void mostartabla2() throws FileNotFoundException, IOException {
        if (arch.exists()) {
            DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
            FileReader fr = new FileReader(arch);
            BufferedReader br = new BufferedReader(fr);
            String y;

            while ((y = br.readLine()) != null) {

                if (y.contains(",")) {

                    String[] campos = y.split(",");
                    String nom = campos[0];
                    Long salmin = Long.parseLong(campos[1]);
                    Long salmax = Long.parseLong(campos[2]);
                    Object parcial = false;
                    if (campos[3].equals("true")) {
                        parcial = true;
                    }
                    Object completa = false;
                    if (campos[4].equals("true")) {
                        completa = true;
                    }
                    String titulacion = campos[5];
                    String habilidad = campos[6];
                    String val = campos[7];
                    String empresatb = campos[8];

                    table.addRow(new Object[]{nom, salmin, salmax, parcial, completa, titulacion, habilidad, val, empresatb});
                }

            }
            br.close();
        }
    }
    
    
    


    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        if ((Nombretf.getText().equals("")) || (Salmintf.getText().equals("")) || (Salmaxtf.getText().equals(""))
                || (Parcial.isSelected() == false && Completa.isSelected() == false) || this.verificarhabilidades() == false
                || Titulacion.getSelectedItem().toString().equals("Escoja titulacion") || nempcb.getSelectedItem().toString().equals("Escoja empresa")) {

            JOptionPane.showMessageDialog(null, "llene todos los campos");
        } else {
            String nom = (Nombretf.getText());
            long salmin = Long.parseLong(Salmintf.getText());
            long salmax = Long.parseLong(Salmaxtf.getText());
            boolean parcial = Parcial.isSelected();
            boolean completa = Completa.isSelected();
            String titulacion = Titulacion.getSelectedItem().toString();
            habilidad="";
            val="";
            
              if (Nivelsl.getSelectedItem().toString() != "Escoja valoracion" && seglen.isSelected()) {
                habilidad = habilidad + "segunda lengua ";
                val = val + Nivelsl.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }

            if (nivelpj.getSelectedItem().toString() != "Escoja valoracion" && projava.isSelected()) {
                habilidad = habilidad + "programacionjava ";
                val = val + nivelpj.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (nivelhc.getSelectedItem().toString() != "Escoja valoracion" && habcom.isSelected()) {
                habilidad = habilidad + "habilidadescomunicativas ";
                val = val + nivelhc.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (nivell.getSelectedItem().toString() != "Escoja valoracion" && lider.isSelected()) {
                habilidad = habilidad + "lider ";
                val = val + nivell.getSelectedItem().toString() + "";
            } else {
                val= val + "0 ";
            }
            if (nivelc.getSelectedItem().toString() != "Escoja valoracion" && crea.isSelected()) {
                habilidad = habilidad + "creativo ";
                val = val + nivelc.getSelectedItem().toString() + " ";
            } else {
                val= val + "0 ";
            }
            if (ningu.isSelected()) {
                habilidad = "ninguno";
                val = "0 0 0 0 0 ";

            }
            
            String empresatb= nempcb.getSelectedItem().toString();
            DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
            table.addRow(new Object[]{nom, salmin, salmax, parcial, completa, titulacion, habilidad, val, empresatb});
            frame.setVisible(false);
            this.setVisible(true);
        }


    }//GEN-LAST:event_insertarActionPerformed

    private void elimbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimbuttonActionPerformed
        if (Tabla.getSelectedRow() == -1){JOptionPane.showMessageDialog(null,"Favor seleccione una fila");}else{
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        table.removeRow(Tabla.getSelectedRow());
        }
    }//GEN-LAST:event_elimbuttonActionPerformed

    private void cleanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanbuttonActionPerformed
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        table.setRowCount(0);
    }//GEN-LAST:event_cleanbuttonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (!arch.exists()) {
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .txt", "txt");
            fc.setFileFilter(filtro);
            int opcion = fc.showSaveDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                arch = fc.getSelectedFile();

            }
        }
        int filas = Tabla.getRowCount();
        DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
        try (FileWriter fw = new FileWriter(arch);
                BufferedWriter bw = new BufferedWriter(fw);) {
            for (int i = 0; i < filas; i++) {
                Object nom = table.getValueAt(i, 0);
                Object salmin = table.getValueAt(i, 1);
                Object salmax = table.getValueAt(i, 2);
                Object parcial = table.getValueAt(i, 3);
                Object completa = table.getValueAt(i, 4);
                Object titulacion = table.getValueAt(i, 5);
                Object habilidad = table.getValueAt(i, 6);
                Object nivel = table.getValueAt(i, 7);
                Object empresatb = table.getValueAt(i, 8);
                bw.write(nom + "," + salmin + "," + salmax + "," + parcial + "," + completa + "," + titulacion + "," + habilidad + "," + nivel + "," + empresatb);
                bw.newLine();
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "Guardado");
        } catch (IOException ex) {
            Logger.getLogger(Demanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .txt", "txt");
        fc.setFileFilter(filtro);
        int opcion = fc.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            arch = fc.getSelectedFile();
            DefaultTableModel table = (DefaultTableModel) Tabla.getModel();
            try (Scanner leer = new Scanner(arch)) {
                while (leer.hasNextLine()) {

                    String linea = leer.nextLine();
                    String[] Datos = linea.split(",");
                    String nom = (Datos[0]);
                    long salmin = Long.parseLong(Datos[1]);
                    long salmax = Long.parseLong(Datos[2]);
                    boolean parcial = Boolean.parseBoolean(Datos[3]);
                    boolean completa = Boolean.parseBoolean(Datos[4]);
                    String titulacion = (Datos[5]);
                    String habilidad = (Datos[6]);
                    String nivel = (Datos[7]);
                    String empresa = (Datos[8]);

                    table.addRow(new Object[]{nom, salmin, salmax, parcial, completa, titulacion, habilidad, nivel, empresa});
                }
                leer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Demanda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_OpenButtonActionPerformed

    private void NombretfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretfActionPerformed

    }//GEN-LAST:event_NombretfActionPerformed

    private void NombretfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombretfKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && ((int) evt.getKeyChar() != 32)) {
            evt.consume();
        }
    }//GEN-LAST:event_NombretfKeyTyped

    private void addbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonMouseEntered

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicio i = new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void SalmintfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalmintfActionPerformed

    }//GEN-LAST:event_SalmintfActionPerformed

    private void SalmintfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalmintfKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_SalmintfKeyTyped

    private void SalmaxtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalmaxtfKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_SalmaxtfKeyTyped

    private void NivelslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NivelslActionPerformed

    private void nivelpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelpjActionPerformed

    private void nivelhcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelhcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelhcActionPerformed

    private void nivellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivellActionPerformed

    private void nivelcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelcActionPerformed

    private void seglenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seglenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seglenActionPerformed

    private void ninguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ninguActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void nempcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nempcbActionPerformed

    }//GEN-LAST:event_nempcbActionPerformed

    private void TitulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulacionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Completa;
    private javax.swing.JComboBox<String> Nivelsl;
    private javax.swing.JTextField Nombretf;
    private javax.swing.JButton OpenButton;
    private javax.swing.JCheckBox Parcial;
    private javax.swing.JTextField Salmaxtf;
    private javax.swing.JTextField Salmintf;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox<String> Titulacion;
    public static javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cleanbutton;
    private javax.swing.JCheckBox crea;
    private javax.swing.JButton elimbutton;
    private javax.swing.JFileChooser fc;
    public static javax.swing.JFrame frame;
    private javax.swing.JCheckBox habcom;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lider;
    public javax.swing.JComboBox<String> nempcb;
    private javax.swing.JCheckBox ningu;
    private javax.swing.JComboBox<String> nivelc;
    private javax.swing.JComboBox<String> nivelhc;
    private javax.swing.JComboBox<String> nivell;
    private javax.swing.JComboBox<String> nivelpj;
    private javax.swing.JCheckBox projava;
    private javax.swing.JCheckBox seglen;
    // End of variables declaration//GEN-END:variables
}
